// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PragmaticBot.Server.Data;

#nullable disable

namespace PragmaticBot.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260915125126_AddDiagnosticLogging")]
    partial class AddDiagnosticLogging
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PragmaticBot.Server.Data.AppLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AdditionalData")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("Category")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("StackTrace")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedUtc");

                    b.ToTable("AppLogs");
                });

            modelBuilder.Entity("PragmaticBot.Server.Data.BetAmountSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BetAmountType")
                        .HasColumnType("int");

                    b.Property<int?>("BettingMethod")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "BetAmountType", "Number")
                        .IsUnique();

                    b.ToTable("BetAmountSettings");
                });

            modelBuilder.Entity("PragmaticBot.Server.Data.BettingAllocation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AllocatedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("BettingHistoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsSent")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("SiteSlot")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("BettingHistoryId");

                    b.ToTable("BettingAllocations");
                });

            modelBuilder.Entity("PragmaticBot.Server.Data.BettingHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("BalanceAfter")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BalanceBefore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("BetAmountType")
                        .HasColumnType("int");

                    b.Property<string>("BetType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GameId")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<bool>("IsVirtual")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("MatrixCol")
                        .HasColumnType("int");

                    b.Property<int?>("MatrixRow")
                        .HasColumnType("int");

                    b.Property<decimal?>("Profit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("SettledUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("TableId")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<decimal?>("WinAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedUtc");

                    b.HasIndex("UserId", "TableId", "GameId", "Status");

                    b.ToTable("BettingHistories");
                });

            modelBuilder.Entity("PragmaticBot.Server.Data.BettingSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("EndBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsVirtual")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("StartBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalBetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedUtc");

                    b.ToTable("BettingSessions");
                });

            modelBuilder.Entity("PragmaticBot.Server.Data.DomainSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BalanceSelector")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("Domain")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("WebSocketUrl")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("Provider")
                        .IsUnique();

                    b.ToTable("DomainSettings");
                });

            modelBuilder.Entity("PragmaticBot.Server.Data.DomainSite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BalanceSelector")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("BrowserType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("DebugPort")
                        .HasColumnType("int");

                    b.Property<string>("Domain")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("SiteSlot")
                        .HasColumnType("int");

                    b.Property<string>("SiteUrl")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("WebSocketUrl")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Provider", "SiteSlot")
                        .IsUnique();

                    b.ToTable("DomainSites");
                });

            modelBuilder.Entity("PragmaticBot.Server.Data.ExceptionFormat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Pattern")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Number")
                        .IsUnique();

                    b.ToTable("ExceptionFormats");
                });

            modelBuilder.Entity("PragmaticBot.Server.Data.FormatSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Number")
                        .IsUnique();

                    b.ToTable("FormatSettings");
                });

            modelBuilder.Entity("PragmaticBot.Server.Data.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DiscoveredUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GameCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<bool>("IsAutoDiscovered")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PpTableId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Provider")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("TitleKo")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Type")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Vendor")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("GameCode")
                        .IsUnique();

                    b.HasIndex("Provider");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("PragmaticBot.Server.Data.LimitSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsLowerLimitEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsTargetCycleEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsUpperLimitEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("KeepAliveTableId")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<decimal?>("LowerLimitPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MaxActiveBettingRooms")
                        .HasColumnType("int");

                    b.Property<int?>("RestIntervalMinutes")
                        .HasColumnType("int");

                    b.Property<int?>("SessionCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("TargetProfitAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UpperLimitMode")
                        .HasColumnType("int");

                    b.Property<decimal?>("UpperLimitPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("LimitSettings");
                });

            modelBuilder.Entity("PragmaticBot.Server.Data.MatrixCell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BetAmountType")
                        .HasColumnType("int");

                    b.Property<int>("ColIndex")
                        .HasColumnType("int");

                    b.Property<int>("RowIndex")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "BetAmountType", "RowIndex", "ColIndex")
                        .IsUnique();

                    b.ToTable("MatrixCells");
                });

            modelBuilder.Entity("PragmaticBot.Server.Data.MatrixRowRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BetAmountType")
                        .HasColumnType("int");

                    b.Property<decimal>("FirstRowCapAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RestMinutes")
                        .HasColumnType("int");

                    b.Property<int>("RowIndex")
                        .HasColumnType("int");

                    b.Property<int>("TargetRow")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WinCount")
                        .HasColumnType("int");

                    b.Property<int>("WinMode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "BetAmountType", "RowIndex")
                        .IsUnique();

                    b.ToTable("MatrixRowRules");
                });

            modelBuilder.Entity("PragmaticBot.Server.Data.Notice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive", "CreatedUtc");

                    b.ToTable("Notices");
                });

            modelBuilder.Entity("PragmaticBot.Server.Data.RoomCooldownSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CooldownMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("LossThreshold")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("RoomCooldownSettings");
                });

            modelBuilder.Entity("PragmaticBot.Server.Data.RoomGateFormat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GateType")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Pattern")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "GateType", "Number")
                        .IsUnique();

                    b.ToTable("RoomGateFormats");
                });

            modelBuilder.Entity("PragmaticBot.Server.Data.StrategyChain", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CompletionAction")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsActive");

                    b.ToTable("StrategyChains");
                });

            modelBuilder.Entity("PragmaticBot.Server.Data.StrategyChainStep", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("ConsecutiveLossTransition")
                        .HasColumnType("int");

                    b.Property<decimal?>("LossAmountTransition")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MaxStepTransition")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<long>("StrategyChainId")
                        .HasColumnType("bigint");

                    b.Property<bool>("StrategyCompleteTransition")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("StrategyType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StrategyChainId");

                    b.ToTable("StrategyChainSteps");
                });

            modelBuilder.Entity("PragmaticBot.Server.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CurrentSessionId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<bool>("DiagnosticLogging")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastHeartbeatUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastIpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime?>("LastLoginUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("TreePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("TreePath");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.HasIndex("ParentId", "Role");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PragmaticBot.Server.Data.UserGameSelection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "GameId")
                        .IsUnique();

                    b.ToTable("UserGameSelections");
                });

            modelBuilder.Entity("PragmaticBot.Server.Data.BettingAllocation", b =>
                {
                    b.HasOne("PragmaticBot.Server.Data.BettingHistory", "BettingHistory")
                        .WithMany("Allocations")
                        .HasForeignKey("BettingHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BettingHistory");
                });

            modelBuilder.Entity("PragmaticBot.Server.Data.DomainSite", b =>
                {
                    b.HasOne("PragmaticBot.Server.Data.User", "User")
                        .WithMany("DomainSites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PragmaticBot.Server.Data.StrategyChainStep", b =>
                {
                    b.HasOne("PragmaticBot.Server.Data.StrategyChain", "StrategyChain")
                        .WithMany("Steps")
                        .HasForeignKey("StrategyChainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StrategyChain");
                });

            modelBuilder.Entity("PragmaticBot.Server.Data.User", b =>
                {
                    b.HasOne("PragmaticBot.Server.Data.User", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("PragmaticBot.Server.Data.BettingHistory", b =>
                {
                    b.Navigation("Allocations");
                });

            modelBuilder.Entity("PragmaticBot.Server.Data.StrategyChain", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("PragmaticBot.Server.Data.User", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("DomainSites");
                });
#pragma warning restore 612, 618
        }
    }
}
